### ISSUE TITLE
Can't run on Windows, issue with missing fuse library

### ISSUE THREAD

**Issue by AshiVered** [bkerler/mtkclient#992]
Win11 Pro 23H2
When runing 
`python mtk_gui`
got error
`Traceback (most recent call last):
  File "C:\Users\Ashi\mtkclient\mtk_gui", line 18, in <module>
    from mtkclient.Library.DA.mtk_da_handler import DA_handler
  File "C:\Users\Ashi\mtkclient\mtkclient\Library\DA\mtk_da_handler.py", line 12, in <module>
    from mtkclient.Library.Filesystem.mtkdafs import MtkDaFS
  File "C:\Users\Ashi\mtkclient\mtkclient\Library\Filesystem\mtkdafs.py", line 1, in <module>
    from fuse import FuseOSError, Operations, LoggingMixIn
  File "C:\Users\Ashi\AppData\Local\Programs\Python\Python311\Lib\site-packages\fuse.py", line 115, in <module>
    raise EnvironmentError('Unable to find libfuse')
OSError: Unable to find libfuse`

https://pypi.org/project/fuse-python/
I check in web, fuse not support Windows

**Comment by sam5610** [comment]
I'm on Win10 Home 22H2 and i have the same issue.

**Comment by farideent** [comment]
I'm on Win10 Home 22H2 and i have the same issue.

**Comment by HXLH50K** [comment]
Same, reset to e33a28d35ac1363b990660c1447952a1495ce9e1 can temporarily solve this problem

**Comment by ColdWindScholar** [comment]
Fixed on https://github.com/bkerler/mtkclient/pull/993

**Comment by sam5610** [comment]
> Fixed on #993 But it seems like there hasn't been a merger?

thanks

**Comment by 4aiman** [comment]
install git-extras as described [here](https://github.com/tj/git-extras/blob/main/Installation.md) and then run 
```
git pr 993
```

**Comment by anthonymesa** [comment]
I am also getting this issue on Windows 11. This issue persists on the pr/993 branch as well as main, where it has been merged. I have also installed winfspy individually, but given that the dll's were included in the commit f8ced92b, I figure that shouldn't be an issue. I also notice that rather it being an issue with 'libfuse' here it is just fuse itself, though the contents of the requirements.txt does include fusepy and I have ensured it is installed on my system. Does anyone have any insight as to what the issue might still be?

``` bash
~\Documents\Applications\mtkclient> git pr 993                                                      06/05/24 13:45:41 PM
Already on 'pr/993'
~\Documents\Applications\mtkclient> python mtk_gui                                                  06/05/24 13:45:49 PM
Traceback (most recent call last):
  File "C:\Users\admes\Documents\Applications\mtkclient\mtk_gui", line 18, in <module>
    from mtkclient.Library.DA.mtk_da_handler import DA_handler
  File "C:\Users\admes\Documents\Applications\mtkclient\mtkclient\Library\DA\mtk_da_handler.py", line 12, in <module>
    from mtkclient.Library.Filesystem.mtkdafs import MtkDaFS
  File "C:\Users\admes\Documents\Applications\mtkclient\mtkclient\Library\Filesystem\mtkdafs.py", line 8, in <module>
    from fuse import Operations, LoggingMixIn
ModuleNotFoundError: No module named 'fuse'
~\Documents\Applications\mtkclient>  
```

**Comment by anthonymesa** [comment]
This did not work for me, using 993 or main after the merger of #993. I have included my details there.

**Comment by bkerler** [comment]
Might be fixed in the release 2.0.1, please test

**Comment by PawiX25** [comment]
@bkerler I'm on version 2.0.1 and using Python 3.11 with Windows 11. I also tried with 3.10 and I keep getting the same error: OSError: Unable to find libfuse.

**Comment by bkerler** [comment]
@PawiX25 ok, will try to test it under Windows next week and sort out the issue :)

**Comment by starterbeeee** [comment]
Hi, not sure if it helps but i got it to run after installing [WinFsp](https://winfsp.dev/rel/).

**Comment by cookie99999** [comment]
WinFsp worked for me as well in Windows 10.

**Comment by htht2001** [comment]
WinFsp also worked for me on Windows 11

**Comment by Necr0m4nc3r** [comment]
Winfsp is the way guys it fixed for me too
